### PR TITLE
Upgrade eleventy from 0.12.1 to 3.0.0

### PR DESCRIPTION
**Pull request by kleinfreund**
Hello! 👋🏻 

This pull request is an attempt to perform a full and working upgrade of your website from Eleventy version 0.12.1 to 3.0.0. I'll first summarize the changes briefly and will go into further detail below.

## Summary

- Update the entire project to use ES module instead of CommonJS syntax. Perhaps this isn't strictly necessary, but it should make future upgrades simpler. (I also noticed that the package gulp-imagemin in its latest versions doesn't provide a CommonJS module anymore so this dependency would have to be downgraded to use CommonJS)
- Fix a syntax error in the site-foot.html partial template where a `{% endif %}` was missing
- Fix the import to the critical CSS generated by the gulp scripts in the base layout not resolving
- Upgrade Eleventy step by step from 0.12.1 to v1, then v2, and finally v3 where only the last step required addressing a few breaking changes
- Remove a few unused imports in the gulp-tasks/fonts.js and src/transforms/parse-transform.js files
- Lastly, I want to point out that the package eleventy-plugin-pwa and also some forks I found are incompatible with Eleventy 3 and unfortunately seem unmaintained. **I was not able to address this break.**

## Details

This pull request contains a series of commits in an attempt to make the process I undertook comprehensible. I'll list the commits and their changes below. If you prefer, the git commits themselves also contain the same content with the exception of the annotations I added here (every time a sentence is prefaced with "Note") and so you can also read this list by running "git log" in your project.

- Revert @11ty/eleventy dependency update from 0.12.1 to 3.0.0

  **Note**: I first reverted the in-progress upgrade of the "@11ty/eleventy" dependency so that I'm first able to achieve a working build of the existing Eleventy site on version 0.12.1

- Use cross-env in front of environment variables so the package scripts work on Windows

  Install the development dependency cross-env and add "cross-env" before the two uses of "NODE_ENV" in the package.json file's "production" script. This allows running the production script on Windows machines, too (as typical shells on Windows don't support setting environment variables with the "NODE_ENV=production" syntax).

  **Note**: This commit is completely optional and can be dropped at will. I only added it because I work on a Windows computer and needed it to make the package scripts work.

- Convert gulpfile and gulp tasks to ES module syntax to fix the production script

  Replace any "require" calls in the gulpfile.js file and all scripts inside "gulp-tasks" with ES module syntax. Replace any uses of "exports" with default or named exports. What used to be "exports.default" was turned into a default export. Any other named CommonJS exports were turned into matching named exports.

- Add missing {% endif %} in site-foot.html partial

  **Note**: This issue is independent from the Eleventy upgrade and if you decide not to incorporate the changes from this pull request, I recommend to incorporate this particular change at least.

- Fix not being able to import critical.css file from dist directory

  Add "../../../dist/" in front of "css/critical.css" in the base.html layout to address the "Error: template not found: css/critical.css" error. Including a file from the "dist" directory is perhaps not ideal, but it does address the error and is a relatively minimal change.

  **Note**: I'm not sure if this fixing an existing issue and, if so, if the fix is appropriated or if it's causing any unintended consequences.

  **Update, Nov 20th, 12.22 am CEST**: This change turned out to be inappropriate (see https://github.com/LJWatson/website-tink-eleventy/pull/26#issuecomment-2488316603). While it fixed the error on Windows, it introduced the same error in UNIX-like environments. The change was reverted in a later commit of this pull request.

- Upgrade Eleventy from 0.12.1 to 1.0.2

  **Note**: [Release notes for reference](https://github.com/11ty/eleventy/releases/tag/v1.0.0)

- Upgrade Eleventy from 1.0.2 to 2.0.1

  **Note**: [Release notes for reference](https://github.com/11ty/eleventy/releases/tag/v2.0.0)

- Upgrade Eleventy from 2.0.1 to 3.0.0

  Upgrade Eleventy and its RSS and syntax highlighting plugins to their respective latest versions. As part of this, a few breaking changes needed to be addressed. Namely, "rssLastUpdatedDate" was replaced with "getNewestCollectionItemDate | dateToRfc3339" in rss.html. Also, "rssDate" was replaced with "dateToRfc3339" in the same file. Furthermore, "post.templateContent" was replaced with "post.content", also in the same file. One thing that I'm unable to address is the incompatibility of the current Eleventy versions with the eleventy-plugin-pwa package which does lead to the error "Package subpath './src/Eleventy' is not defined by 'exports'" during the Eleventy build process. However, this does not prevent the site from building correctly as far as I can tell. There doesn't seem to be a direct fork of the package that is still maintained so I'm unable to address this break.

  Convert the remaining JavaScript files in the project (i.e. the Eleventy config file and related filter and transform scripts) to use ES module syntax to make future updates and migrations simpler. The changes are exclusively a search-and-replace of all remaining "require" calls with their "import" equivalent and of all remaining "module.exports =" with "export default". Also, set the type field in the package.json file to "module".

  **Note**: [Release notes for reference](https://github.com/11ty/eleventy/releases/tag/v3.0.0)

- Add .nvmrc file in an attempt to fix the Netlify deployment previews

  Netlify will read the .nvmrc file to determine the Node.js (and therefore npm) version to use when running the build command. Such a file will override the Netlify UI configuration. For more information, read https://docs.netlify.com/configure-builds/manage-dependencies/.

  **Note**: I used the Node.js version 22.11.0 in the .nvmrc file following the advice of the project's readme to use the current LTS version.

- Disable eleventy-plugin-pwa in an attempt to fix the Netlify deployment previews

  Disable eleventy-plugin-pwa. After configuring a compatible Node.js version previously to attempt to fix the Netlify deployment, the build still fails on account of the eleventy-plugin-pwa-caused errors during the "npm run production" execution. Since the PWA plugin is incompatible with Eleventy 3 anyway, disabling it should do away with those errors.

- Revert earlier change to the critical CSS include

  In an earlier commit, I fixed an issue I encountered in a Windows system where the line '{% include "css/critical.css" %}' caused a 'Error: template not found: css/critical.css (via Template render error)' error. However, while that fix addressed the issue, it broke the include in UNIX environments where now that very same error occurs. Reverting it leaves the include broken in Windows but should fix both the owner's build issue and also the Netlify deployment previews.

- Fix sass gulp task for Windows

  Use the platform-specific path separator variable from Node's `path` builtin to split the `history` variable instead of a hard-coded slash. This way, the sass gulp task works identically for both UNIX-like platforms and Windows.

## Netlify deployment previews

I noticed that pull requests have Netlify deployment previews enabled but that they seem to fail currently.

In the Netlify environment, I see Node.js v12.18.0 and npm 6.14.4 being used. While working on this pull request, I used Node.js v22.11.0 and npm 10.9.0.

Perhaps updating the versions in Netlify can help address this.

**Update, Nov 20th, 11.24 am CEST**: After adding an `.nvmrc` file to the root of the project (which Netlify uses to determine the Node.js version to install), the initial issues seen in the Netlify logs are solved. The build still fails, but now the cause is different. It's now the error that occurs during `npm run production` relating to the incompatibility between the `eleventy-plugin-pwa` and `@11ty/eleventy` packages.

**Update, Nov 2th, 11.33 am CEST**: After disabling the Eleventy PWA plugin, the Netlify deployment previews still don't work as there is yet another error during the execution of "npm run build": "Error: template not found: /opt/build/repo/dist/css/critical.css (via Template render error)". This one, for the time being, isn't comprehensible to me. Running the same command locally does not produce this error and the Netlify logs show that the critical.css file is being produced. After some fiddling, I noticed that this error also happens in my local Linux environment.

### CODE REVIEW

**Comment by kleinfreund** [comment]
I noticed an issue with the pull request in its current state after I checked out its branch in a Linux environment. For me, `npm run production` fails with the following error:

```
Error: template not found: /home/phil/dev/website-tink-eleventy/dist/css/critical.css
```

This is likely also the cause for the Netlify deployment previews to still fail.

**Comment by kleinfreund** [comment]
I confirmed my suspicion in my previous comment: my "fix" of the `{% include "css/critical.css" %}` line that does break on my Windows machine did break UNIX-like environments by causing the exact same error in those environments that I attempted to fix in my Windows one.

With that "fix" reverted, the production script should work again and also, we should now have actually working Netlify deployment previews: https://deploy-preview-26--elated-thompson-d04e53.netlify.app/

**Comment by kleinfreund** [comment]
I've decided to add one more change here: to fix the production script on Windows, too, but this time properly. I eventually found the root cause of the critical CSS include not working Windows. The issue was relying on a forward slash as the path separator which broke the sass gulp task on Windows. This is now fixed, too.

**Comment by LJWatson** [comment]
@kleinfreund I cannot thank you enough for your help with this, and on Masto. It was incredibly generous of you and if I can ever return the favour with anything accessibility related, please don't hesitate to reach out.

**Pull request merged**
